config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/send_mail' => 'home#send_mail'
  resources :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_mail.rb
class UserMail
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :message

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def send_mail
    begin
      @user = UserMail.new(safe_params)
      UserMailer.send_message(@user).deliver
    rescue => e
      @error = e.message
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def safe_params
    params.permit(:name, :email, :subject, :message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.new
  end

  def create
    @post = Post.new(post: safe_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def safe_params
    params.require(:post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message(msg)
    html = ''
    html << "<div class=' alert alert-danger'>"
    html << "<strong>ERROR!</strong> #{msg}"
    html << "</div>"
    html
  end

  def success_for(msg)
    html = ''
    html << "<div class='alert alert-success '>"
    html << "<strong>SUCCESS!</strong> #{msg}"
    html << "</div>"
    html
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_about.html.haml
%section#about.about-section.section-padding
  .container
    %h2.section-title.wow.fadeInUp About Me
    .row
      .col-md-4.col-md-push-8
        .biography
          .myphoto
            =image_tag('myphoto.jpg')
          %ul
            %li
              %strong Name:
              Ekansh Sharma
            %li
              %strong Date of birth:
              11 Nov 1993
            %li
              %strong Address:
              340, 4th Avenue Street, HSR Layout 5th Sector, Bengalore, India
            %li
              %strong Nationality:
              Indian
            %li
              %strong Phone:
              8553891591
            %li
              %strong Email:
              ekanshsharmacse11@gmail.com
      / col-md-4
      .col-md-8.col-md-pull-4
        .short-info.wow.fadeInUp
          %h3 Objective
          %p An opportunity to work and upgrade oneself, as well as being involved in an organization that believes in gaining a competitive edge and giving back to the community. I'm presently expanding my solid experience in Software Development. I focus on using my interpersonal skills to build good user experience. I hope to develop skills and my knowledge of the Web, and become an honest asset to the business. As an individual, I'm self-confident you’ll find me creative, funny and naturally passionate. I’m a forward thinker, which others may find inspiring when working as a team.
        .short-info.wow.fadeInUp
          %h3 What I Do ?
          %p I have been working as a full stack developer since 1 year 9 months. I have a love of clean, elegant coding, and I have lots of experience in the production of ruby on rails, javascript and angularjs. I loving creating awesome as per my clients need.
          %ul.list-check
            %li BackEnd Programming
            %li FrontEnd Programming
            %li Ruby on rails
            %li AngularJs
            %li Javascript
            %li HTML
        .my-signature
          =image_tag('sign.png', height: '60px', width: '150px')
        .download-button
          %a.btn.btn-info.btn-lg{:href => "#contact"}
            %i.fa.fa-paper-plane>
            Send me message
          %a.btn.btn-primary.btn-lg{:href => "ekansh-sharma-cv.pdf"}
            %i.fa.fa-download>
            download my cv

app/views/home/_blog.html.haml
%section#blog.latest-blog-section.section-padding
  .container
    %h2.section-title.wow.fadeInUp Latest Post
    .row
      .col-sm-4
        %article.blog-post-wrapper
          .figure
            .post-thumbnail
              %a{:href => "#"}
                = image_tag('blog/01.jpg', class: 'img-responsive')
            %i.fa.fa-file-photo-o
          %header.entry-header
            .post-meta
              %span.the-category
                %a{:href => "#"} Ruby on Rails
            %h2.entry-title
              %a{:href => "#", :rel => ""} Use omniauth to authorize with fb,github and other social web.
            %hr/
            .entry-meta
              %ul.list-inline
                %li
                  %span.the-author
                    %a{:href => "#"} Admin
                %li
                  %span.the-time
                    %a{:href => "#"} 06 Jan 2015
      .col-sm-4
        %article.blog-post-wrapper
          .figure
            .post-thumbnail
              %a{:href => "#"}
                = image_tag('blog/02.jpg', class: 'img-responsive', style: 'height: 166px')
            %i.fa.fa-file-video-o
          %header.entry-header
            .post-meta
              %span.the-category
                %a{:href => "#"} Ruby on rails
            %h2.entry-title
              %a{:href => "#", :rel => ""} Use paprclip gem to upload image.
            %hr/
            .entry-meta
              %ul.list-inline
                %li
                  %span.the-author
                    %a{:href => "#"} Admin
                %li
                  %span.the-time
                    %a{:href => "#"} 06 Jan 2015
      .col-sm-4
        %article.blog-post-wrapper
          .figure
            .post-thumbnail
              %a{:href => "#"}
                = image_tag('blog/03.jpg', class: 'img-responsive',style: 'height: 166px')
            %i.fa.fa-quote-left
          %header.entry-header
            .post-meta
              %span.the-category
                %a{:href => "#"} Ruby on Rails
            %h2.entry-title
              %a{:href => "#", :rel => ""} Create shopping cart for e-website.
            %hr/
            .entry-meta
              %ul.list-inline
                %li
                  %span.the-author
                    %a{:href => "#"} Admin
                %li
                  %span.the-time
                    %a{:href => "#"} 06 Jan 2015
                %li
                  %span.the-share
                    %a{:href => "#", :title => "share"} 30
                %li
                  %span.the-comments
                    %a{:href => "#", :title => ""} 05
    .blog-more.text-center
      %a.btn.btn-primary{:href => "#"} View More

app/views/home/_contact.html.haml
%section#contact.contact-section.section-padding
  .container
    %h2.section-title.wow.fadeInUp Get in touch
    .row
      .col-md-6
        .contact-form
          %strong Send me a message
          #show_message
          = form_tag(home_send_mail_path, remote: true) do
            .form-group
              = label_tag 'name'
              = text_field_tag('name', '', id: 'name', class: 'form-control', required: true)
            .form-group
              = label_tag 'email'
              = email_field_tag('email', '', id: 'email', class: 'form-control', required: true)
            .form-group
              = label_tag 'subject'
              = text_field_tag('subject', '', id: 'subject', class: 'form-control', required: true)
            .form-group
              = label_tag 'message'
              = text_area_tag('message', '',id: 'message', class: 'form-control', rows: 5, required: true)
            = submit_tag('Send Message', class: 'btn btn-primary')
      .col-md-6
        .row.center-xs
          .col-sm-6
            %i.fa.fa-map-marker
            %address
              %strong Address/Street
              340, 4th Avenue Street, HSR Layout 5th Sector,
              %br/
              Bengalore, India
              %br/
          .col-sm-6
            %i.fa.fa-mobile
            .contact-number
              %strong Phone Number
              +91 8553891591
        .row
          .col-sm-12
            .location-map
              #mapCanvas.map-canvas

app/views/home/_fact.html.haml
%section#facts.facts-section.text-center{"data-stellar-background-ratio" => "0.2", "data-stellar-vertical-offset" => "50"}
  .tt-overlay-bg
    .container
      .row
        .col-md-12
          .count-wrap
            .col-sm-3.col-xs-6
              %i.fa.fa-flask
              %h3.timer 1
              %p Years of Experience
            .col-sm-3.col-xs-6
              %i.fa.fa-thumbs-up
              %h3.timer 4
              %p Projects Done
            .col-sm-3.col-xs-6
              %i.fa.fa-users
              %h3.timer 1
              %p Happy Clients
            .col-sm-3.col-xs-6
              %i.fa.fa-trophy
              %h3.timer 4
              %p Awards Won

app/views/home/_hire.html.haml
%section.hire-section.text-center{"data-stellar-background-ratio" => "0.2", "data-stellar-vertical-offset" => "50"}
  .hire-section-bg
    .container
      .row
        .col-md-12
          %h2 I'm available for freelance project
          %a.btn.btn-default{:href => "#"} Get Hired

app/views/home/_home.html.haml
%section#home.tt-fullHeight{"data-stellar-background-ratio" => "0.2", "data-stellar-vertical-offset" => "50"}
  .intro
    .intro-sub I am Ekansh Sharma
    %h1
      Full Stack
      %span Developer
    %p
      I am a fully professional Developer
      %br/
      Involving with latest technologies.
      %br/
      Feel free to contact.
    .social-icons
      %ul.list-inline
        %li
          %a{:href => "https://github.com/Ekansh-Sharma"}
            %i.fa.fa-github
        %li
          %a{:href => "https://in.linkedin.com/in/sharmaekansh"}
            %i.fa.fa-linkedin
        %li
          %a{:href => "https://www.facebook.com/ekansh.sharma.921"}
            %i.fa.fa-facebook
        %li
          %a{:href => "https://twitter.com/ekanshsharma18"}
            %i.fa.fa-twitter
  .mouse-icon
    .wheel

app/views/home/_navigation.html.haml
%header.header
  %nav.navbar.navbar-custom{:role => "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => "#custom-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        / <a class="navbar-brand" href="index.html"><img src="assets/images/logo.png" alt=""></a>
      #custom-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to('Home', '#home')
          %li
            = link_to('About', '#about')
          %li
            = link_to('Resume', '#resume')
          %li
            = link_to('Skills', '#skills')
          %li
            = link_to('Works', '#works')
          %li
            = link_to('Blog', posts_path)
          %li
            = link_to('Contact', '#contact')

app/views/home/_resume.html.haml
%section#resume.resume-section.section-padding
  .container
    %h2.section-title.wow.fadeInUp Resume
    .row
      .col-md-12
        .resume-title
          %h3 Education
        .resume
          %ul.timeline
            %li
              .posted-date
                %span.month 20011-2015
              .timeline-panel.wow.fadeInUp
                .timeline-content
                  .timeline-heading
                    %h3 Bachelor degree certificate
                    %span NIT Arunachal Pradesh, Yupia, India
                  .timeline-body
                    %p I have completed bachelor degree from NIT Arunachal Pradesh, Yupia, India at feel the charm of existence in this spot, which was create.
            %li.timeline-inverted
              .posted-date
                %span.month 2009-2010
              .timeline-panel.wow.fadeInUp
                .timeline-content
                  .timeline-heading
                    %h3 Higher Secondary certificate
                    %span S.M.B Inter College, Aligarh, India
                  .timeline-body
                    %p From this college of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend.
            %li
              .posted-date
                %span.month 2007-2008
              .timeline-panel.wow.fadeInUp
                .timeline-content
                  .timeline-heading
                    %h3 Secondary school certificate
                    %span S.M.B Inter College, Aligarh, India
                  .timeline-body
                    %p I was awesome at math, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy.
    .row
      .col-md-12
        .resume-title
          %h3 Experience
        .resume
          %ul.timeline
            %li.timeline-inverted
              .posted-date
                %span.month 2015-Current
              .timeline-panel.wow.fadeInUp
                .timeline-content
                  .timeline-heading
                    %h3 Full Stack Developer
                    %span Cybrilla Technologies, Bengalore
                  .timeline-body
                    %p I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend.

app/views/home/_skill.html.haml
%section#skills.skills-section.section-padding
  .container
    %h2.section-title.wow.fadeInUp Skills
    .row
      .col-md-6
        .skill-progress
          .skill-title
            %h3 Ruby
          .progress
            .progress-bar.six-sec-ease-in-out{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "95", :role => "progressbar"}
              %span 80%
          / /.progress
        / /.skill-progress
        .skill-progress
          .skill-title
            %h3 Rails
          .progress
            .progress-bar.six-sec-ease-in-out{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar"}
              %span 70%
          / /.progress
        / /.skill-progress
        .skill-progress
          .skill-title
            %h3 Business Logic
          .progress
            .progress-bar.six-sec-ease-in-out{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "75", :role => "progressbar"}
              %span 80%
          / /.progress
        / /.skill-progress
      / /.col-md-6
      .col-md-6
        .skill-progress
          .skill-title
            %h3 AngularJs
          .progress
            .progress-bar.six-sec-ease-in-out{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "95", :role => "progressbar"}
              %span 80%
          / /.progress
        / /.skill-progress
        .skill-progress
          .skill-title
            %h3 Javascript
          .progress
            .progress-bar.six-sec-ease-in-out{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar"}
              %span 70%
          / /.progress
        / /.skill-progress
        .skill-progress
          .skill-title
            %h3 HTML
          .progress
            .progress-bar.six-sec-ease-in-out{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "75", :role => "progressbar"}
              %span 80%
          / /.progress
        / /.skill-progress
      / /.col-md-6
    / /.row
    .skill-chart.text-center
      %h3 More skills
    .row.more-skill.text-center
      .col-xs-12.col-sm-4.col-md-2
        .chart{"data-color" => "e74c3c", "data-percent" => "90"}
          %span.percent
          .chart-text
            %span Leadership
      .col-xs-12.col-sm-4.col-md-2
        .chart{"data-color" => "2ecc71", "data-percent" => "80"}
          %span.percent
          .chart-text
            %span Creativity
      .col-xs-12.col-sm-4.col-md-2
        .chart{"data-color" => "3498db", "data-percent" => "50"}
          %span.percent
          .chart-text
            %span Management
      .col-xs-12.col-sm-4.col-md-2
        .chart{"data-color" => "3498db", "data-percent" => "90"}
          %span.percent
          .chart-text
            %span Goal Oriented
      .col-xs-12.col-sm-4.col-md-2
        .chart{"data-color" => "3498db", "data-percent" => "85"}
          %span.percent
          .chart-text
            %span Team Player
      .col-xs-12.col-sm-4.col-md-2
        .chart{"data-color" => "3498db", "data-percent" => "90"}
          %span.percent
          .chart-text
            %span Motivation

app/views/home/_video.html.haml
/   / /.container
/ / End Skills Section
/ / Video Section
/ /
/   <section id="video" class="video-section">
/   <div class="tf-bg-overlay">
  
/   <div class="container">
  
/   <div class="video-intro">
/   <a class="popup-video" href="https://www.youtube.com/watch?v=LGOjcu0HRec"> <i class="fa fa-play"></i>  </a>
/   <h2>Video Introducing</h2>
/   </div>
  
/   </div>
  
/   <!--/.container
/ / /.overlay
/ \--&gt;
/ / /.Video Section

app/views/home/_work.html.haml
%section#works.works-section.section-padding
  .container
    %h2.section-title.wow.fadeInUp Works
    %ul#filter.list-inline
      %li
        %a.active{"data-group" => "all"} All
      %li
        %a{"data-group" => "design"} Design
      %li
        %a{"data-group" => "web"} Web
      %li
        %a{"data-group" => "interface"} Interface
      %li
        %a{"data-group" => "identety"} Identity
    .row
      #grid
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"identety\", \"interface\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{ href: "#{asset_path('works/portfolio-2.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-2.jpg', height: '180px')
              .portfolio-info
                %h3 Platform
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"identety\", \"web\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-1.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-1.jpg', height: '180px')
              .portfolio-info
                %h3 Ruby On Rails
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"interface\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-7.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-7.jpg', height: '180px')
              .portfolio-info
                %h3 Operating System
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"identety\", \"design\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-4.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-4.jpg', height: '180px')
              .portfolio-info
                %h3 Javascript
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"identety\", \"design\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-3.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-3.jpg', height: '180px')
              .portfolio-info
                %h3 AngularJs
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"identety\", \"design\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-6.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-6.jpg', height: '180px')
              .portfolio-info
                %h3 Algorithm
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"identety\", \"web\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-5.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-5.jpg', height: '180px')
              .portfolio-info
                %h3 Data Structure
        .portfolio-item.col-xs-12.col-sm-4.col-md-3{"data-groups" => "[\"all\", \"design\"]"}
          .portfolio-bg
            .portfolio
              .tt-overlay
              .links
                %a.image-link{:href => "#{asset_path('works/portfolio-8.jpg')}"}
                  %i.fa.fa-search-plus
                %a{:href => "#"}
                  %i.fa.fa-link
              = image_tag('works/portfolio-8.jpg', height: '180px')
              .portfolio-info
                %h3 Github

app/views/home/index.html.haml
#tt-preloader
  #pre-status
    .preload-placeholder
= render 'home'
= render 'navigation'
= render 'about'
= render 'skill'
= render 'resume'
= render 'work'
= render 'fact'
= render 'blog'
= render 'hire'
= render 'contact'
%footer.footer-wrapper
  .container
    .row
      .col-md-12
        .copyright.text-center
          %p © All rights reserved.
.scroll-up
  %a{:href => "#home"}
    %i.fa.fa-angle-up

app/views/home/send_mail.js.haml
- if @error.present?
  $("#show_message").html("#{ escape_javascript(error_message(@error).html_safe)}");
- else
  $("#show_message").html("#{ escape_javascript(success_for('Successfully Sent.').html_safe)}");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ekansh
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag('https://fonts.googleapis.com/css?family=Roboto:400,300,500,700')
    = javascript_include_tag 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyANlIn3OWmA77tfI--7oZBphXT6ydaHLb0'
    = csrf_meta_tags
  %body
    = yield

app/views/posts/index.html.haml
#posts
  .container
    .row.main
      .panel-heading
        .panel-title.text-center
          %h1.title Ekansh's Blog
          %hr/
      .main-login.main-center
        %form.form-horizontal{:action => "#", :method => "post"}
          .form-group
            %label.cols-sm-2.control-label{:for => "email"} Your Email
            .cols-sm-10
              .input-group
                %span.input-group-addon
                  %i.fa.fa-envelope.fa{"aria-hidden" => "true"}
                %input#email.form-control{:name => "email", :placeholder => "Enter your Email", :type => "text"}/

          .form-group
            %label.cols-sm-2.control-label{:for => "password"} Password
            .cols-sm-10
              .input-group
                %span.input-group-addon
                  %i.fa.fa-lock.fa-lg{"aria-hidden" => "true"}
                %input#password.form-control{:name => "password", :placeholder => "Enter your Password", :type => "password"}/

          .form-group
            %button.btn.btn-primary.btn-lg.btn-block.login-button{:type => "button"} Login

app/views/posts/new.html.haml
.container
  .col-md-12
    .form-area
      = form_tag('/posts') do
        %br{:style => "clear:both"}/
        %h3{:style => "margin-bottom: 25px; text-align: center;"} Create Blog
        .form-group
          = text_field_tag('post[category]','',placeholder: 'Category', required: true, class: 'form-control', id: 'name')
        .form-group
          = text_field_tag('post[email]','',placeholder: 'Email', required: true, class: 'form-control', id: 'email')
        .form-group
          = text_field_tag('post[mobile]','',placeholder: 'Mobile', required: true, class: 'form-control', id: 'mobile')
        .form-group
          = text_field_tag('post[title]','',placeholder: 'Title', required: true, class: 'form-control', id: 'title')
        .form-group
          = text_area_tag('post[message]','',placeholder: 'Message', required: true, class: 'form-control', id: 'message', rows: "7")
        = submit_tag('Submit Form', class: 'btn btn-primary center-block', id: 'submit')